<?php
set_include_path(__DIR__.'/../app'.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.__DIR__.'/../src'.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.__DIR__.'/../public'.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.__DIR__.'/..'.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.__DIR__.'/../app/storage'.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.__DIR__.DIRECTORY_SEPARATOR
	.PATH_SEPARATOR.get_include_path()
	);

